language: javascript

sudo: required

before_deploy:
  - "npm install && npm run build:prod"
  - "echo 'ready!'"

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file: builds/kuna-*.zip
  skip_cleanup: true
  on:
    tags: true