export enum Events {

    REGISTER = 'REGISTER',
    CLOSE_POPUP = 'CLOSE_POPUP',

    GET_TICKERS = 'FETCH_TICKERS',
    UPDATE_TICKER = 'UPDATE_TICKER',
    FETCH_CURRENT_TICKER = 'FETCH_CURRENT_TICKER',
    SET_CURRENT_TICKER = 'SET_CURRENT_TICKER'
}
